FROM golang:alpine3.14 AS builder

WORKDIR /go/src
RUN mkdir fullcycle
WORKDIR /go/src/fullcycle
RUN go mod init desafio/fullcycle
COPY FullcycleRocks.go /go/src/fullcycle
RUN go build desafio/fullcycle

FROM scratch
COPY --from=builder /go/src/fullcycle/fullcycle /go/bin/fullcycle
ENTRYPOINT ["/go/bin/fullcycle"] 